services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow:
    build:
      context: .
    container_name: airflow
    ports:
      - "8080:8080" # Keeps Airflow web server accessible on port 8080
    depends_on:
      - postgres
    networks:
      - airflow_network

networks:
  airflow_network:
    external: false

volumes:
  postgres_data:
